### ISSUE TITLE
flying sword

### ISSUE THREAD

**Issue by fadoartpokebr** [DaoOfModding/Cultivationcraft#2]
How can i get a flying sword? i already see in the commands that you have an entity called flying sword is that possible to get?

**Comment by fadoartpokebr** [comment]
obs: your mod is so cool pls continue working on it

**Comment by DaoOfModding** [comment]
Hi, flying swords were actually one of the first things implemented in the Mod - however they were made for internal cultivation, which is not currently implemented, so unfortunately there is no way currently to 'get' (I write 'get', but it actually just makes any sword item fly around and attack) them.

**Comment by fadoartpokebr** [comment]
oh ok thank you
